name: cnine
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - pytorch
  # So this setup works, somewhat
  #  - it installs $CUDA_HOME into $CONDA_PREFIX (run: export CUDA_HOME=$CONDA_PREFIX) before
  #  - something is unhappy after, which prevents packages from being added. But it compiles.
  - cuda-toolkit
  - pytorch-cuda
